### ISSUE TITLE
Could not upload your report with feedbacks, seems like i dont have rights to do it.

### ISSUE THREAD

**Issue by istemi-bahceci** [CS319-G12/uMonopoly#1]

**Comment by anikristo** [comment]
I have been using Bitbucket before and in order to have group contributions there you just create a team. Here it is a bit different as I understand, you first create an organization then a team based on the organization members? I did this now, maybe it works ... @istemi-bahceci

**Comment by istemi-bahceci** [comment]
It is ok now, thanks for fast workaround :)
